### ISSUE TITLE
Поддержка Bots Long Poll API

### ISSUE THREAD

**Issue by Jengas** [vk-brain/sketal#108]
Разработчики VK недавно выпустили Bots Long Poll API. Будет ли бот поддерживать это?

**Comment by Yardanico** [comment]
Ну так-то Bots Long Poll API это просто Callback API с вызывами как у Longpoll API, так что это не должно быть сложно

**Comment by michaelkrukov** [comment]
Он поддерживает на ветке 8.0
https://github.com/vk-brain/sketal/blob/dev-v8.0/run.py
