### ISSUE TITLE
Ошибка с ботом в ветке dev-v8.0

### ISSUE THREAD

**Issue by Jengas** [vk-brain/sketal#109]
### 
![image](https://user-images.githubusercontent.com/14033756/42128395-8f1bc8c6-7caa-11e8-99aa-b378c1da9fd2.png)

**Comment by Syndykat** [comment]
Там же написано, ты скорее всего вынес эту строку за класс или функцию. Проверь для начало

**Comment by Yardanico** [comment]
@Jengas похоже что ты испортил индентацию кода (кол-во пробелов перед кодом) на этой строке. И да, dev-ветка не обязана быть рабочей (чаще всего она рабочая, но она не обязана быть рабочей)

**Comment by Jengas** [comment]
Перекачал dev ветку заново, и все заработало.

**Comment by Yardanico** [comment]
@Jengas только на будущее - с Git не нужно "перекачивать", нужно клонировать репозиторий и потом делать git pull
