### ISSUE TITLE
Simple Webhook to post a message to conversation

### ISSUE THREAD

**Issue by ohld** [vk-brain/sketal#118]
Здравствуйте.

Меня очень интересует возможность писать сообщение в чат с большим количеством пользователей. Это не чат группы-паблика, а аналог `Group chat` телеги. 

В телеге есть аналогичный вебхук, который мне нужен для вк:

```
https://api.telegram.org/bot<ТОКЕН>/sendMessage?chat_id=<CHAT_ID>&text=TEXT
```

Есть ли аналогичный вебхук для VK?

Есть ли функционал в вашем боте, который позволяет просто отправлять сообщение в такие чаты? 

PS. Я опытный Python разработчик.

**Comment by michaelkrukov** [comment]
Здравствуйте.

> Это не чат группы-паблика, а аналог Group chat телеги.

Речь идёт о беседах вконтакте? Они являются обычными беседами, с которыми на данный момент Sketal может работать в беседах только от лица пользователя. Поддержка групп в беседах с помощью Sketal на данный момент не планируется, однако очень активно развивается (v0.2.4, что очень свежо) проект ["Kutana"](https://github.com/vk-brain/kutana), который работает из-под группы и работает в беседах.

> В телеге есть аналогичный вебхук, который мне нужен для вк:
>> https://api.telegram.org/bot<ТОКЕН>/sendMessage?chat_id=<CHAT_ID>&text=TEXT

Это выглядит как обычный запрос к API телеграма (а не webhook). Немого посмотрев  документацию API Телеграма, там написано, что это метод для отправки сообщения. Это соответствует по функционалу методу ВК API - https://vk.com/dev/messages.send

> Есть ли функционал в вашем боте, который позволяет просто отправлять сообщение в такие чаты?

Если нужно только отправлять - нет необходимости использовать какие-либо движки. Отправка сообщения - это один HTTP запрос. Движки для ботов, такие как Sketal, организовывают получение сообщений и ответ на них с помощью плагинов.  

> PS. Я опытный Python разработчик.

Спасибо, что предупредили.

**Comment by michaelkrukov** [comment]
В каком смысле беседы с большим числом людей? Группы могут находится в беседах так-же, как и пользователи. Если речь идёт о каких-то незадокументированных разработках (или о чём-то, о чём я не знаю) - то я не могу дать квалифицированный ответ. Однако я знаю, что группы сейчас - лучший вариант для любых ботов.

**Comment by ohld** [comment]
Может быть, я непонятно выразился.

Задача: в `group chat` добавить возможность писать сообщения скриптом. Желательно не с личного профиля, а с профиля / аккаунта бота (по аналогии с Телеграмм).

Под `group chat` я имел в виду тот чат, который можно создать, нажимая на большой "плюс" в сообщениях.

<img width="334" alt="image" src="https://user-images.githubusercontent.com/5613295/45258004-77333880-b3b8-11e8-849e-ceab8a28d074.png">

**Comment by michaelkrukov** [comment]
Именно это и есть обычная беседа, в которой могут состоять группы, если их туда добавят. И метод, который я прислал работает как для пользователей, так и для групп без проблем.

**Comment by ohld** [comment]
Спасибо!
