### ISSUE TITLE
Upgrade ChatterPlugin

### ISSUE THREAD

**Issue by michaelkrukov** [vk-brain/sketal#74]
Добавить инструкции с приставкой n (negate (обратить)), для расширения возможностей.
Добавить инструкции v1, v2 ... v8 для присваивания переменных(1-8) и их использование в ответах.

**Comment by MrBrikster** [comment]
Поддержки ChatterBot не будет?

**Comment by michaelkrukov** [comment]
@MrBrikster потенциально планиурется
