### ISSUE TITLE
батя сдох

### ISSUE THREAD

**Issue by batyapixelya** [vk-brain/sketal#75]
### Ожидаемый результат (что должно было произойти)
батя сдох
### Фактический результат (что произошло на самом деле)
батя сдох
### Как повторить эту ошибку? 
батя сдох
### Дополнительная информация (какие настройки, работает-ли всё остальное, какие плагины используюся)
батя сдохбатя сдохбатя сдохбатя сдохбатя сдохбатя сдохбатя сдохбатя сдохбатя сдох

**Comment by Yardanico** [comment]
Won't fix. Батя здох
