### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by arseny2606** [vk-brain/sketal#87]
### Ожидаемый результат (что должно было произойти, чего вы ожидали)
бот должен был запуститься
### Фактический результат (что произошло на самом деле, что не должно было произойти или должно было произойти иначе)
вылетела ошибка
### Как повторить эту ошибку? (код, который вызвал ошибку, настройки)
python bot.py
### Дополнительная информация (лог ошибок, какие настройки использовались, какую версию python используете)
python 3.6.4, api.py     [18.03.08 18:07:04] WARNING : Can't execute code: "return [API.messag
es.getLongPollServer({ "use_ssl":1,"lp_version":2})];"
bot.py     [18.03.08 18:07:05] ERROR   : Unable to connect to VK's long polling
server

**Comment by michaelkrukov** [comment]
Проверьте свои данные в настройках, убедитесь, что вы можете зайти на vk.com, убедитесь что ваш токен (если вы его используете) имеет небходимые права. Ошибка подразумевает, что не получет ответ от ВК.

**Comment by arseny2606** [comment]
я использую свои логин и пароль. Зайти на аккаунт могу.

**Comment by michaelkrukov** [comment]
Недостаточно информации для воспроизведения ошибки. Бот работает при аналогичных условиях.

**Comment by arseny2606** [comment]
C:\Users\user\Desktop\sketal-master>bot.py     [18.03.08 18:07:05] ERROR   : Una
ble to connect to VK's long polling
bot.py     [18.03.08 18:09:41] INFO    : Initializing bot
bot.py     [18.03.08 18:09:41] INFO    : Initializing vk clients
bot.py     [18.03.08 18:09:41] INFO    : Loading plugins
sayer.py   [18.03.08 18:09:41] WARNING : You are using public key for Speechkit
Cloud! Get your own: https://tech.yandex.ru/speechkit/cloud/
bot.py     [18.03.08 18:09:41] INFO    : Bot successfully initialized
bot.py     [18.03.08 18:09:41] INFO    : Started to process messages
api.py     [18.03.08 18:09:42] WARNING : Can't execute code: "return [API.messag
es.getLongPollServer({ "use_ssl":1,"lp_version":2})];"
api.py     [18.03.08 18:09:43] WARNING : Can't execute code: "return [API.messag
es.getLongPollServer({ "use_ssl":1,"lp_version":2})];"
api.py     [18.03.08 18:09:44] WARNING : Can't execute code: "return [API.messag
es.getLongPollServer({ "use_ssl":1,"lp_version":2})];"
api.py     [18.03.08 18:09:46] WARNING : Can't execute code: "return [API.messag
es.getLongPollServer({ "use_ssl":1,"lp_version":2})];"
api.py     [18.03.08 18:09:47] WARNING : Can't execute code: "return [API.messag
es.getLongPollServer({ "use_ssl":1,"lp_version":2})];"
api.py     [18.03.08 18:09:48] WARNING : Can't execute code: "return [API.messag
es.getLongPollServer({ "use_ssl":1,"lp_version":2})];"
api.py     [18.03.08 18:09:49] WARNING : Can't execute code: "return [API.messag
es.getLongPollServer({ "use_ssl":1,"lp_version":2})];"
api.py     [18.03.08 18:09:51] WARNING : Can't execute code: "return [API.messag
es.getLongPollServer({ "use_ssl":1,"lp_version":2})];"
api.py     [18.03.08 18:09:52] WARNING : Can't execute code: "return [API.messag
es.getLongPollServer({ "use_ssl":1,"lp_version":2})];"
api.py     [18.03.08 18:09:53] WARNING : Can't execute code: "return [API.messag
es.getLongPollServer({ "use_ssl":1,"lp_version":2})];"
bot.py     [18.03.08 18:10:01] ERROR   : Unable to connect to VK's long polling
server
bot.py     [18.03.08 18:10:01] INFO    : Stopped to process messages

**Comment by michaelkrukov** [comment]
Покажите настройки. Вполне вероятно, что вы неверно ввели свой логин/пароль.

**Comment by arseny2606** [comment]
я работаю с токеном

**Comment by michaelkrukov** [comment]
Покажите настройки. Есть вероятность, что вы неверно ввели свой токен.

**Comment by arseny2606** [comment]
настройки в setting.py?

**Comment by Yardanico** [comment]
@arseny2606 покажите настройки, и вместо своего токена напишите "TOKEN"

**Comment by arseny2606** [comment]
нашёл ошибку, не там заполнял
