### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by arseny2606** [vk-brain/sketal#89]
### Ожидаемый результат (что должно было произойти, чего вы ожидали)
Запуск
### Фактический результат (что произошло на самом деле, что не должно было произойти или должно было произойти иначе)
Он пишет, что надо ввести капчу, но содержимое файла tempcaptcha.png картинка с надписью "нет доступа"
### Как повторить эту ошибку? (код, который вызвал ошибку, настройки)
python bot.py
### Дополнительная информация (лог ошибок, какие настройки использовались, какую версию python используете)
C:\Users\user\Desktop\sketal-master>bot.py
bot.py     [18.03.09 11:13:06] INFO    : Initializing bot
bot.py     [18.03.09 11:13:06] INFO    : Initializing vk clients
auth.py    [18.03.09 11:13:08] WARNING : (this can be caused by wrong login/pass
word!)
api.py     [18.03.09 11:13:08] WARNING : Enter information for captcha solving i
n settings.py
Enter captcha from file `tempcaptcha.png`:

**Comment by DiSonDS** [comment]
В логах же все написано

**Comment by arseny2606** [comment]
Я понял, неправильные логин и пароль, но они правильные

**Comment by DiSonDS** [comment]
@arseny2606 значит вы до этого вводили неверные данные. Сейчас вас бот просит указать сервис и ключ для распознавания капчи в settings.py

**Comment by arseny2606** [comment]
@DiSonDS, сервис указан. Где ключ взять?

**Comment by DiSonDS** [comment]
@arseny2606 зарегистрируйтесь, оплатите, получите.

**Comment by arseny2606** [comment]
а по-другому никак?

**Comment by eqlient** [comment]
Нет.

**Comment by michaelkrukov** [comment]
@arseny2606 Поскольку капчи на самом деле нет, то это значит, но не удаётся войти в аккаунт. Попробуйте использовать токен с максимальными правами.

**Comment by arseny2606** [comment]
@michaelkrukov, спасибо, заработало
