### ISSUE TITLE
Проблема с "Русской рулеткой"

### ISSUE THREAD

**Issue by itsdiosron** [vk-brain/sketal#90]
### Ожидаемый результат (что должно было произойти, чего вы ожидали)
Должна была начаться игра "Русская рулетка"
### Фактический результат (что произошло на самом деле, что не должно было произойти или должно было произойти иначе)
Ответа бота не последовало, произошла ошибка в консоли
### Как повторить эту ошибку? (код, который вызвал ошибку, настройки)
Использовался PeeweePlugin подключённый к MySQL базе и плагин на игру "Русская рулетка" "RussianRoulettePlugin"
### Дополнительная информация (лог ошибок, какие настройки использовались, какую версию python используете)
python3.6.4 , для данного теста использовались плагины: PeeweePlugin и RussianRoulettePlugin 
![image](https://user-images.githubusercontent.com/36332367/37251364-c9223146-251f-11e8-940d-10c057c15db7.png)
![image](https://user-images.githubusercontent.com/36332367/37251365-d62c08a8-251f-11e8-89e8-1535b35a49fa.png)

**Comment by michaelkrukov** [comment]
Я совершенно не знаю, в чём проблема. Ошибка, похоже, возникает из-за некорректной работы MySQL, peewee и peewee_async. Можно использовать другую БД или попробовать другие версии модулей. Было бы неплохо, если бы кто-нибудь помог с этим ( ͡° ͜ʖ ͡°)

**Comment by itsdiosron** [comment]
Проблема решилась использованием PostgreSQL
