### ISSUE TITLE
Duels / Актив

### ISSUE THREAD

**Issue by Daeeros** [vk-brain/sketal#91]
/del

**Comment by michaelkrukov** [comment]
Duels должен находится в самом верху, для того, чтобы он грамотно всё отслеживал.

**Comment by Daeeros** [comment]
Даже поверх peewwe, admins, и chatmeta?

**Comment by michaelkrukov** [comment]
Это является загадкой, т.к. по факту не должно быть таких проблем. Точно ниже peewee, chatmeta и admins, дальше, наверное, как захочется.

**Comment by Daeeros** [comment]
Сделал так как вы сказали, все так же, человек активил в течении часа, но актив прописался  0.06,  как я понял, бот посчитал лишь его команду принятия, и правда загадочно)

**Comment by michaelkrukov** [comment]
Если вы только что подвинули - то атив за прошедший час никак не может измениться.

**Comment by Daeeros** [comment]
Тестировал уже в другой конференции, с другим человеком.

**Comment by michaelkrukov** [comment]
12 минут назад вы передвинули плагин, потом пишете, что "человек активил в течении часа". Только это не играет никакой роли, т.к. предположительно в это время бот работал некорректно. Подождите, проверьте, оцените всё по справедливости и отпишитесь о результатах.

**Comment by Daeeros** [comment]
Хорошо, отпишу через 2 часа

**Comment by Daeeros** [comment]
Все так же, извините за задержку, ладно пусть будет как есть. Спасибо за помощь, удачи вам.
