### ISSUE TITLE
Ошибка при установке модулей

### ISSUE THREAD

**Issue by ilovetwilight** [vk-brain/sketal#93]
![image](https://user-images.githubusercontent.com/37379880/38769513-ed374faa-400c-11e8-8546-5f8a7c28a2be.png)
![image](https://user-images.githubusercontent.com/37379880/38769517-fab5a1e0-400c-11e8-8604-f8ebdfabc1f4.png)

**Comment by Yardanico** [comment]
Ваша VPS не может установить HTTPS соединение с сайтом, это не проблема бота.

**Comment by Yardanico** [comment]
Ваша версия Python'а собрана без поддержки SSL
