### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by arseny2606** [vk-brain/sketal#94]
### Ожидаемый результат (что должно было произойти, чего вы ожидали)
запуск бота
### Фактический результат (что произошло на самом деле, что не должно было произойти или должно было произойти иначе)
ошибка
### Как повторить эту ошибку? (код, который вызвал ошибку, настройки)
python bot.py
### Дополнительная информация (лог ошибок, какие настройки использовались, какую версию python используете)
вроде как 3.6, так как 2.7 удалил.
```
 `C:\Users\Samsung\Desktop\Арсений\sketal-master>python bot.py
Traceback (most recent call last):
  File "bot.py", line 387, in <module>
    from settings_real import BotSettings
ModuleNotFoundError: No module named 'settings_real'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 390, in <module>
    from settings import BotSettings
  File "C:\Users\Samsung\Desktop\Арсений\sketal-master\settings.py", line 21, in
 <module>
    class BotSettings(BaseSettings):
  File "C:\Users\Samsung\Desktop\Арсений\sketal-master\settings.py", line 86, in
 BotSettings
    QuotePlugin("цитатка"),
  File "C:\Users\Samsung\Desktop\Арсений\sketal-master\plugins\content\quote\quo
te.py", line 24, in __init__
    self.f = ImageFont.truetype(self.get_path("font.ttf"), 20)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python36-32\lib\site-pack
ages\PIL\ImageFont.py", line 260, in truetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python36-32\lib\site-pack
ages\PIL\ImageFont.py", line 143, in __init__
    self.font = core.getfont(font, size, index, encoding, layout_engine=layout_e
ngine)
OSError: cannot open resource

C:\Users\Samsung\Desktop\Арсений\sketal-master>`
```

**Comment by michaelkrukov** [comment]
Скорее всего, у бота недостаточно прав для открытия файлов (в частности, для шрифта для плагина `quote`). Можно попробовать запускать с правами администратора или попытаться разобратьсяс правами на файлы и папки.

**Comment by Yardanico** [comment]
Ещё может быть проблема из-за кириллических символов в пути

**Comment by arseny2606** [comment]
Теперь он при установке модулей пишет ‘’’command python setup.py egg_info failed with error code 1 in /tmp/pip-build-ZRW4qy/aiohttp’’’

**Comment by Yardanico** [comment]
@arseny2606 полный лог можно? Мы не экстрасенсы

**Comment by arseny2606** [comment]
@yardanico позже

**Comment by arseny2606** [comment]
Лог при установке модулей 
Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl 
Collecting aiohttp (from -r requirements.txt (line 3)) 
 Downloading https://files.pythonhosted.org/packages/81/fa/8915137ac0603112bbb63489de90a75c69da8a138594eb6a24cb8afb14df/aiohttp-3.2.1.tar.gz (720kB) 
 100% |################################| 727kB 683kB/s 
 Complete output from command python setup.py egg_info: 
 Traceback (most recent call last): 
 File "<string>", line 1, in <module> 
 File "/tmp/pip-build-2slYd1/aiohttp/setup.py", line 2, in <module> 
 import pathlib 
 ImportError: No module named pathlib 
 
 —------------------------------------— 
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2slYd1/aiohttp/ 
You are using pip version 8.1.1, however version 10.0.1 is available. 
You should consider upgrading via the 'pip install —upgrade pip' command.

**Comment by SevastyanDark** [comment]
Что выводит 'python --version'?

**Comment by Yardanico** [comment]
@arseny2606 вы же понимаете, что это не относится к боту, это отдельная проблема с вашим питоном/его настройкой?
