### ISSUE TITLE
Каким образом происходит работа с беседами?

### ISSUE THREAD

**Issue by zelkor** [vk-brain/sketal#95]
Каким образом происходит работа с беседами? Ведь сообщество нельзя добавить в беседу. Или надо использовать _свой_ токен, а бот будет производить действия от моего имени?

**Comment by michaelkrukov** [comment]
Cообщество нельзя добавить в беседу. Бот поддерживает работу как от лица пользователя, так и от лица группы. Всё написано в readme в 4 пункте раздела "Инструкция".

**Comment by zelkor** [comment]
@michaelkrukov нужно ли при этом убирать токен сообщества? И при работе от лица пользователя бот обрабатывает сообщения от любых других собеседников в беседе или только от создателя?

**Comment by michaelkrukov** [comment]
Бот работает от лица первого указанного токена - группы или пользователя. Бот обрабатывает все входящие сообщения.

**Comment by zelkor** [comment]
Ясно, спасибо!
